### ISSUE TITLE
Cannot get this working

### ISSUE THREAD

**Issue by dustinupdyke** [Tron5000/HealthGraphNet#3]
Getting issues with NuGet or compile from scratch:

> An exception of type 'System.MissingMethodException' occurred in HealthGraphNet.dll but was not handled in user code
> Additional information: Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.Uri)'.

**Comment by gabornemeth** [comment]
Maybe a newer version of RestSharp  broke the binary compatibility with the one used for compiling HealthGraphNet 1.0.
You can try using 2.0 version of HealthGraphNet. See https://github.com/Tron5000/HealthGraphNet/issues/6#issuecomment-277433855
