### ISSUE TITLE
Support of other platforms

### ISSUE THREAD

**Issue by gabornemeth** [Tron5000/HealthGraphNet#4]
I have forked your repo and added support of Android, iOS, PCL. Moved to using RestSharp.Portable. Would you consider merging those changes and publish new nuget packages? I can help creating the nuspec files or even upload packages if you give me rights to the package :) If these changes against your concept or if this project is not maintained further, I'll have to modify my fork and publish packages under a different name.
Anyway, thank you for such a great work.

**Comment by Tron5000** [comment]
That sounds awesome! I don't have time to maintain HealthGraphNet much anymore but would appreciate help, if you're willing.  I've invited you to be a collaborator of the repro - have fun.  :-)

Do you have a NuGet username? If so, I'll make you an owner of the package as well.

**Comment by gabornemeth** [comment]
Thank you :)
My NuGet username is also 'gabornemeth'

**Comment by Tron5000** [comment]
I've added you as an owner of the NuGet package. Thanks again!

**Comment by gabornemeth** [comment]
I'd try to upload a new version to NuGet, but it seems i don't have the required permission.

**Comment by Tron5000** [comment]
<img width="822" alt="nuget" src="https://cloud.githubusercontent.com/assets/348929/22633377/b5cc6c58-ebd5-11e6-891b-4a6fff371f6d.png">

Do you have to sign in to NuGet and accept the pending invitation?

**Comment by gabornemeth** [comment]
Could you possibly resend the invitation? I cannot figure out on nuget.org how I should accept it, and don't have the notification e-mail anymore.

**Comment by Tron5000** [comment]
I removed and re-invited you to be an owner of the NuGet package.  Did you receive a new invite?

**Comment by gabornemeth** [comment]
Thank you. I accepted the invite, now it's working fine.
