### ISSUE TITLE
depends on RestSharp 103.4.0

### ISSUE THREAD

**Issue by lhp620** [Tron5000/HealthGraphNet#6]
After installing HealthGarphNet1.0, I found it depends on RestSharp 103.4.0, which is very old and release in 2012. If I have other API need to be called in the same project, but which is depends on RestSharp 105 version, I do not know how to make sure there is no conflict between them.

**Comment by gabornemeth** [comment]
You can try assembly version redirection in app.config to use the newer version of RestSharp.
Although version 1.0 is not maintained further, 2.0 depends on RestSharp.Portable.

**Comment by dialogmanager** [comment]
Thanks, how to install 2.0? Install-Package HealthGraphNet 2.0 or Install-Package HealthGraphNet 2 does not work for me.

**Comment by lhp620** [comment]
Thanks, how to install 2.0? Install-Package HealthGraphNet 2.0 or Install-Package HealthGraphNet 2 does not work for me.

Oh, I saw another thread. Is it possible you release a Nuget with new name before you get the permission to update HealthGraphNet. Once you got permission, delete the temp one and update the original one. Thanks a lot for the help.

**Comment by gabornemeth** [comment]
Temporarily you can get from the following feed: https://www.myget.org/F/gabornemeth/api/v3/index.json
2.0.2 is the latest version.

**Comment by lhp620** [comment]
Thanks for the reply. how to start use the version 2.0? I build the DLLs from this project and 
I tried to use the NET45 version HealthGraphNet related DLLs in project like:
```
            var authenticator = new StaticAuthenticator() { AccessToken = token.access_token };
            Client TokenManager = new Client(authenticator);

            UserRequest = new UsersEndpoint(TokenManager);
            var user = await UserRequest.GetUser();

               var activitiesReques = new FitnessActivitiesEndpoint(tokenManager, user);
                var feedpage = await activitiesReques.GetFeedPage();
                var activity = activitiesReques.GetActivity(feedpage.Items[0].Uri);
                return activity.Result.Distance;
```

The response I got is: Id = 222, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}". 

(I can make sure the accesstoken is correct).

**Comment by gabornemeth** [comment]
Your use case seems right. This use case is tested in integration tests too, and it works there.

I'll update the samples and docs soon.

**Edit:** I see you modified the code. Is feedpage variable correct now? Last time there was a problem if my memory serves me right.
Does the following not work?
```
  var activity = await activitiesRequest.GetActivity(feedpage.Items[0].Uri);
  return activity.Distance;
```

**Comment by lhp620** [comment]
Thanks. feedpage still has problem with my project, but if I just created a console project and import these DLLs, it worked amazing. so I am looking why userEndpoint works, but FitnessActivity Endpoint does not work in my project. 

The problem is I forgot an await in my project, works now. Thanks a lot for the help gabornemeth
